---
- name: assert | set fact for amount of hosts
  set_fact:
    host_count: "{{ ansible_play_hosts | length }}"

- name: assert | set fact for roles
  set_fact:
    mongo_primary: "{{ mongo_replication_role == 'primary' }}"
    mongo_secondary: "{{ mongo_replication_role == 'secondary' }}"
    mongo_arbiter: "{{ mongo_replication_role == 'arbiter' }}"

- block:

    - name: assert | create dictionary of bootstrappers
      set_fact:
        primaries: "{{ dict(keys|zip(values)) }}"
      vars:
        keys: "{{ ansible_play_hosts }}"
        values: "{{ ansible_play_hosts|
                    map('extract', hostvars, ['mongo_primary']) |
                    list }}"

    - name: assert | create list of bootstrappers
      set_fact:
        primary_list: "{{ primaries | dict2items |
                       selectattr('value') |
                       map(attribute='key') |
                       list }}"

    - name: assert | create dictionary of bootstrappers
      set_fact:
        arbiters: "{{ dict(keys|zip(values)) }}"
      vars:
        keys: "{{ ansible_play_hosts }}"
        values: "{{ ansible_play_hosts|
                    map('extract', hostvars, ['mongo_arbiter']) |
                    list }}"

    - name: assert | create list of arbiters
      set_fact:
        arbiter_list: "{{ arbiters | dict2items |
                       selectattr('value') |
                       map(attribute='key') |
                       list }}"

  run_once: true
  when: host_count != '1'
