---
- name: conf | set
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  register: mongo_conf_set

- name: conf | ensure mongod is started and enabled
  service:
    name: mongod
    state: started
    enabled: true

- name: conf | restart mongo
  service:
    name: mongod
    state: restarted

- name: conf | await some time until mongo restarted
  ansible.builtin.pause:
    seconds: 10
